name: strings
version: 1.0.0
description: Provides a set of String related functions
repository: https://github.com/onepub-dev/strings
environment: 
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies: 
  lint_hard: ^3.0.0
  test: ^1.0.0
dependencies:
  characters: ^1.3.0
  unicode: ^0.3.1
