name: strings
version: 2.0.1
documentation: https://strings.onepub.dev
description: Provides a set of String related aimed at extending the core String class and provide safer methods for working with nullable strings and strings in general.
repository: https://github.com/onepub-dev/strings
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  characters: ^1.3.0
  unicode: ^0.3.1
dev_dependencies: 
  lint_hard: ^3.0.0
  test: ^1.0.0
